### Настройки DevSecOps ###
### Общая информация о командах ###
team:
  - {
    # код команды в МУСе
    mus_code: "00FV0048",
    # название команды в МУСе
    mus_name: "КАП. SDP Hadoop Ozone",
    # Почтовый адрес Product Owner в МУСе для уведомлений с результатами сканирования
    # !!! Почта должна быть валидной для текущего домена, чтобы корректно определить пользователя, которому впоследствии предоставятся права на доступ к АС в SALM !!!
    # !!! Возможно указание нескольких почт через знаки ";" или "," внутри одной строки !!!
    # Пример: "user1@sberbank.ru; user2@sberbank.ru, user3@sberbank.ru"
    mus_po_mail: "Orlov.s.andre@sberbank.ru",
  }
  # Возможно добавление нескольких команд
  # !!! Вторую и последующие команды необходимо добавить по формату, аналогичному первой !!!
#  - {
#      mus_code: "00040018",
#      mus_name: "Web SBOL Design",
#      mus_po_mail: "sspetrov@sberbank.ru",
#    }

### Общая информация о приложении ###
app:
  # Конфигурационный элемент (КЭ) приложения / модуля ПО в Service Manager.
  # !!! КЭ должен быть строкой, состоящей исключительно из цифр без лидирующих нулей !!!
  sm_id: "3756734"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "КАП ТС Хранение данных КАП в SberData Platform Hadoop"

### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование
  creds_id: "SDP_CxCreds_2"
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "SDP"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана.
  # Пример: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  masks: ""
  # id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения. 100003 - Smoke
  preset_id: "36"
  # макс время ожидания статуса QG в минутах
  wait_qg: "-1"

### Настройки OSS
oss:
  # Маски файлов и директорий для исключения из сканирования
  # Пример: "**/utils/**/*.xml" - исключение всех xml файлов во всех папках utils
  # !!! Перечисление нескольких масок возможно через знаки "," или ";" внутри одной строки, например, "**/*test*/**; **/*.txt, .git/**" !!!
  # !!! Пропуски в каждой маске справа и слева автоматически удалятся (trim) !!!
  excludes: ".git/**, **/*.tar.gz, **/*test*/**"
